//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ticeWS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documento
    {
        public int codigoDocumento { get; set; }
        public Nullable<int> codigoCurso { get; set; }
        public Nullable<int> codigoActividad { get; set; }
        public Nullable<int> codigoTarea { get; set; }
        public string titulo { get; set; }
        public string autor { get; set; }
        public Nullable<int> codigoTipoDocumento { get; set; }
        public string descripcion { get; set; }
        public string rutaDocumento { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public string usuarioCreacion { get; set; }
        public string usuarioModificacion { get; set; }
    }
}
