//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ticeWS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ticeEntities3 : DbContext
    {
        public ticeEntities3()
            : base("name=ticeEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AsignacionCurso> AsignacionCurso { get; set; }
        public virtual DbSet<Tarea> Tarea { get; set; }
        public virtual DbSet<Documento> Documento { get; set; }
        public virtual DbSet<Curso> Curso { get; set; }
        public virtual DbSet<Docente> Docente { get; set; }
    
        public virtual ObjectResult<SP_ACTIVIDAD_RETRIEVE_BY_CURSO_Result> SP_ACTIVIDAD_RETRIEVE_BY_CURSO(string periodo, string estado)
        {
            var periodoParameter = periodo != null ?
                new ObjectParameter("periodo", periodo) :
                new ObjectParameter("periodo", typeof(string));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ACTIVIDAD_RETRIEVE_BY_CURSO_Result>("SP_ACTIVIDAD_RETRIEVE_BY_CURSO", periodoParameter, estadoParameter);
        }
    
        public virtual int SP_ACTIVIDAD_CREATE(Nullable<int> codigoCurso, Nullable<int> codigoModalidad, Nullable<int> codigoPeriodo, Nullable<int> codigoTipoCurso, string titulo, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, Nullable<int> codigoSesion, Nullable<int> codigoEstado, string descripcion, string usuarioCreacion)
        {
            var codigoCursoParameter = codigoCurso.HasValue ?
                new ObjectParameter("codigoCurso", codigoCurso) :
                new ObjectParameter("codigoCurso", typeof(int));
    
            var codigoModalidadParameter = codigoModalidad.HasValue ?
                new ObjectParameter("codigoModalidad", codigoModalidad) :
                new ObjectParameter("codigoModalidad", typeof(int));
    
            var codigoPeriodoParameter = codigoPeriodo.HasValue ?
                new ObjectParameter("codigoPeriodo", codigoPeriodo) :
                new ObjectParameter("codigoPeriodo", typeof(int));
    
            var codigoTipoCursoParameter = codigoTipoCurso.HasValue ?
                new ObjectParameter("codigoTipoCurso", codigoTipoCurso) :
                new ObjectParameter("codigoTipoCurso", typeof(int));
    
            var tituloParameter = titulo != null ?
                new ObjectParameter("titulo", titulo) :
                new ObjectParameter("titulo", typeof(string));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("fechaFin", fechaFin) :
                new ObjectParameter("fechaFin", typeof(System.DateTime));
    
            var codigoSesionParameter = codigoSesion.HasValue ?
                new ObjectParameter("codigoSesion", codigoSesion) :
                new ObjectParameter("codigoSesion", typeof(int));
    
            var codigoEstadoParameter = codigoEstado.HasValue ?
                new ObjectParameter("codigoEstado", codigoEstado) :
                new ObjectParameter("codigoEstado", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var usuarioCreacionParameter = usuarioCreacion != null ?
                new ObjectParameter("usuarioCreacion", usuarioCreacion) :
                new ObjectParameter("usuarioCreacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ACTIVIDAD_CREATE", codigoCursoParameter, codigoModalidadParameter, codigoPeriodoParameter, codigoTipoCursoParameter, tituloParameter, fechaInicioParameter, fechaFinParameter, codigoSesionParameter, codigoEstadoParameter, descripcionParameter, usuarioCreacionParameter);
        }
    
        public virtual int SP_ACTIVIDAD_DELETE(Nullable<int> codigoActividad)
        {
            var codigoActividadParameter = codigoActividad.HasValue ?
                new ObjectParameter("codigoActividad", codigoActividad) :
                new ObjectParameter("codigoActividad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ACTIVIDAD_DELETE", codigoActividadParameter);
        }
    
        public virtual int SP_ACTIVIDAD_UPDATE(Nullable<int> codigoActividad, Nullable<int> codigoCurso, Nullable<int> codigoModalidad, Nullable<int> codigoPeriodo, Nullable<int> codigoTipoCurso, string titulo, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, Nullable<int> codigoSesion, Nullable<int> codigoEstado, string descripcion, string usuarioModificacion, Nullable<System.DateTime> fechaModificacion)
        {
            var codigoActividadParameter = codigoActividad.HasValue ?
                new ObjectParameter("codigoActividad", codigoActividad) :
                new ObjectParameter("codigoActividad", typeof(int));
    
            var codigoCursoParameter = codigoCurso.HasValue ?
                new ObjectParameter("codigoCurso", codigoCurso) :
                new ObjectParameter("codigoCurso", typeof(int));
    
            var codigoModalidadParameter = codigoModalidad.HasValue ?
                new ObjectParameter("codigoModalidad", codigoModalidad) :
                new ObjectParameter("codigoModalidad", typeof(int));
    
            var codigoPeriodoParameter = codigoPeriodo.HasValue ?
                new ObjectParameter("codigoPeriodo", codigoPeriodo) :
                new ObjectParameter("codigoPeriodo", typeof(int));
    
            var codigoTipoCursoParameter = codigoTipoCurso.HasValue ?
                new ObjectParameter("codigoTipoCurso", codigoTipoCurso) :
                new ObjectParameter("codigoTipoCurso", typeof(int));
    
            var tituloParameter = titulo != null ?
                new ObjectParameter("titulo", titulo) :
                new ObjectParameter("titulo", typeof(string));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("fechaFin", fechaFin) :
                new ObjectParameter("fechaFin", typeof(System.DateTime));
    
            var codigoSesionParameter = codigoSesion.HasValue ?
                new ObjectParameter("codigoSesion", codigoSesion) :
                new ObjectParameter("codigoSesion", typeof(int));
    
            var codigoEstadoParameter = codigoEstado.HasValue ?
                new ObjectParameter("codigoEstado", codigoEstado) :
                new ObjectParameter("codigoEstado", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var usuarioModificacionParameter = usuarioModificacion != null ?
                new ObjectParameter("usuarioModificacion", usuarioModificacion) :
                new ObjectParameter("usuarioModificacion", typeof(string));
    
            var fechaModificacionParameter = fechaModificacion.HasValue ?
                new ObjectParameter("fechaModificacion", fechaModificacion) :
                new ObjectParameter("fechaModificacion", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ACTIVIDAD_UPDATE", codigoActividadParameter, codigoCursoParameter, codigoModalidadParameter, codigoPeriodoParameter, codigoTipoCursoParameter, tituloParameter, fechaInicioParameter, fechaFinParameter, codigoSesionParameter, codigoEstadoParameter, descripcionParameter, usuarioModificacionParameter, fechaModificacionParameter);
        }
    
        public virtual int SP_TAREA_CREATE(Nullable<int> codigoCurso, Nullable<int> codigoActividad, string titulo, Nullable<int> codigoPrioridad, string estado, Nullable<int> porcentajeCompletado, Nullable<int> codigoRecurso, string descripcion, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, string usuarioCreacion)
        {
            var codigoCursoParameter = codigoCurso.HasValue ?
                new ObjectParameter("codigoCurso", codigoCurso) :
                new ObjectParameter("codigoCurso", typeof(int));
    
            var codigoActividadParameter = codigoActividad.HasValue ?
                new ObjectParameter("codigoActividad", codigoActividad) :
                new ObjectParameter("codigoActividad", typeof(int));
    
            var tituloParameter = titulo != null ?
                new ObjectParameter("titulo", titulo) :
                new ObjectParameter("titulo", typeof(string));
    
            var codigoPrioridadParameter = codigoPrioridad.HasValue ?
                new ObjectParameter("codigoPrioridad", codigoPrioridad) :
                new ObjectParameter("codigoPrioridad", typeof(int));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            var porcentajeCompletadoParameter = porcentajeCompletado.HasValue ?
                new ObjectParameter("porcentajeCompletado", porcentajeCompletado) :
                new ObjectParameter("porcentajeCompletado", typeof(int));
    
            var codigoRecursoParameter = codigoRecurso.HasValue ?
                new ObjectParameter("codigoRecurso", codigoRecurso) :
                new ObjectParameter("codigoRecurso", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("fechaFin", fechaFin) :
                new ObjectParameter("fechaFin", typeof(System.DateTime));
    
            var usuarioCreacionParameter = usuarioCreacion != null ?
                new ObjectParameter("usuarioCreacion", usuarioCreacion) :
                new ObjectParameter("usuarioCreacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TAREA_CREATE", codigoCursoParameter, codigoActividadParameter, tituloParameter, codigoPrioridadParameter, estadoParameter, porcentajeCompletadoParameter, codigoRecursoParameter, descripcionParameter, fechaInicioParameter, fechaFinParameter, usuarioCreacionParameter);
        }
    
        public virtual int SP_TAREA_DELETE(Nullable<int> codigoTarea)
        {
            var codigoTareaParameter = codigoTarea.HasValue ?
                new ObjectParameter("codigoTarea", codigoTarea) :
                new ObjectParameter("codigoTarea", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TAREA_DELETE", codigoTareaParameter);
        }
    
        public virtual ObjectResult<SP_TAREA_RETRIEVE_BY_ACTIVIDAD_Result> SP_TAREA_RETRIEVE_BY_ACTIVIDAD(Nullable<int> codigoActividad)
        {
            var codigoActividadParameter = codigoActividad.HasValue ?
                new ObjectParameter("codigoActividad", codigoActividad) :
                new ObjectParameter("codigoActividad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TAREA_RETRIEVE_BY_ACTIVIDAD_Result>("SP_TAREA_RETRIEVE_BY_ACTIVIDAD", codigoActividadParameter);
        }
    
        public virtual int SP_TAREA_UPDATE(Nullable<int> codigoTarea, Nullable<int> codigoCurso, Nullable<int> codigoActividad, string titulo, Nullable<int> codigoPrioridad, string estado, Nullable<int> porcentajeCompletado, Nullable<int> codigoRecurso, string descripcion, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, Nullable<System.DateTime> fechaModificacion, string usuarioModificacion)
        {
            var codigoTareaParameter = codigoTarea.HasValue ?
                new ObjectParameter("codigoTarea", codigoTarea) :
                new ObjectParameter("codigoTarea", typeof(int));
    
            var codigoCursoParameter = codigoCurso.HasValue ?
                new ObjectParameter("codigoCurso", codigoCurso) :
                new ObjectParameter("codigoCurso", typeof(int));
    
            var codigoActividadParameter = codigoActividad.HasValue ?
                new ObjectParameter("codigoActividad", codigoActividad) :
                new ObjectParameter("codigoActividad", typeof(int));
    
            var tituloParameter = titulo != null ?
                new ObjectParameter("titulo", titulo) :
                new ObjectParameter("titulo", typeof(string));
    
            var codigoPrioridadParameter = codigoPrioridad.HasValue ?
                new ObjectParameter("codigoPrioridad", codigoPrioridad) :
                new ObjectParameter("codigoPrioridad", typeof(int));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            var porcentajeCompletadoParameter = porcentajeCompletado.HasValue ?
                new ObjectParameter("porcentajeCompletado", porcentajeCompletado) :
                new ObjectParameter("porcentajeCompletado", typeof(int));
    
            var codigoRecursoParameter = codigoRecurso.HasValue ?
                new ObjectParameter("codigoRecurso", codigoRecurso) :
                new ObjectParameter("codigoRecurso", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("fechaFin", fechaFin) :
                new ObjectParameter("fechaFin", typeof(System.DateTime));
    
            var fechaModificacionParameter = fechaModificacion.HasValue ?
                new ObjectParameter("fechaModificacion", fechaModificacion) :
                new ObjectParameter("fechaModificacion", typeof(System.DateTime));
    
            var usuarioModificacionParameter = usuarioModificacion != null ?
                new ObjectParameter("usuarioModificacion", usuarioModificacion) :
                new ObjectParameter("usuarioModificacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TAREA_UPDATE", codigoTareaParameter, codigoCursoParameter, codigoActividadParameter, tituloParameter, codigoPrioridadParameter, estadoParameter, porcentajeCompletadoParameter, codigoRecursoParameter, descripcionParameter, fechaInicioParameter, fechaFinParameter, fechaModificacionParameter, usuarioModificacionParameter);
        }
    
        public virtual ObjectResult<SP_DOCUMENTO_RETRIEVE_BY_TAREA_Result> SP_DOCUMENTO_RETRIEVE_BY_TAREA(Nullable<int> codigoTarea)
        {
            var codigoTareaParameter = codigoTarea.HasValue ?
                new ObjectParameter("codigoTarea", codigoTarea) :
                new ObjectParameter("codigoTarea", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DOCUMENTO_RETRIEVE_BY_TAREA_Result>("SP_DOCUMENTO_RETRIEVE_BY_TAREA", codigoTareaParameter);
        }
    
        public virtual ObjectResult<SP_CAPACITACION_LOAD_Result> SP_CAPACITACION_LOAD(Nullable<int> codigoTaller, Nullable<int> codigoPeriodo, string nombreCapacitacion)
        {
            var codigoTallerParameter = codigoTaller.HasValue ?
                new ObjectParameter("codigoTaller", codigoTaller) :
                new ObjectParameter("codigoTaller", typeof(int));
    
            var codigoPeriodoParameter = codigoPeriodo.HasValue ?
                new ObjectParameter("codigoPeriodo", codigoPeriodo) :
                new ObjectParameter("codigoPeriodo", typeof(int));
    
            var nombreCapacitacionParameter = nombreCapacitacion != null ?
                new ObjectParameter("nombreCapacitacion", nombreCapacitacion) :
                new ObjectParameter("nombreCapacitacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CAPACITACION_LOAD_Result>("SP_CAPACITACION_LOAD", codigoTallerParameter, codigoPeriodoParameter, nombreCapacitacionParameter);
        }
    
        public virtual ObjectResult<SP_MATERIAL_CAPACITACION_RETRIEVE_BY_CAPACITACION_Result> SP_MATERIAL_CAPACITACION_RETRIEVE_BY_CAPACITACION(Nullable<int> codigoCapacitacion)
        {
            var codigoCapacitacionParameter = codigoCapacitacion.HasValue ?
                new ObjectParameter("codigoCapacitacion", codigoCapacitacion) :
                new ObjectParameter("codigoCapacitacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MATERIAL_CAPACITACION_RETRIEVE_BY_CAPACITACION_Result>("SP_MATERIAL_CAPACITACION_RETRIEVE_BY_CAPACITACION", codigoCapacitacionParameter);
        }
    
        public virtual int SP_PARTICIPANTES_CAPACITACION_CREATE(Nullable<int> codigoDocente, Nullable<int> codigoCapacitacion, string nombreCompleto, Nullable<bool> enviarconvocatoria)
        {
            var codigoDocenteParameter = codigoDocente.HasValue ?
                new ObjectParameter("codigoDocente", codigoDocente) :
                new ObjectParameter("codigoDocente", typeof(int));
    
            var codigoCapacitacionParameter = codigoCapacitacion.HasValue ?
                new ObjectParameter("codigoCapacitacion", codigoCapacitacion) :
                new ObjectParameter("codigoCapacitacion", typeof(int));
    
            var nombreCompletoParameter = nombreCompleto != null ?
                new ObjectParameter("nombreCompleto", nombreCompleto) :
                new ObjectParameter("nombreCompleto", typeof(string));
    
            var enviarconvocatoriaParameter = enviarconvocatoria.HasValue ?
                new ObjectParameter("enviarconvocatoria", enviarconvocatoria) :
                new ObjectParameter("enviarconvocatoria", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PARTICIPANTES_CAPACITACION_CREATE", codigoDocenteParameter, codigoCapacitacionParameter, nombreCompletoParameter, enviarconvocatoriaParameter);
        }
    
        public virtual ObjectResult<SP_PARTICIPANTES_CAPACITACION_RETRIEVE_BY_CAPACITACION_Result> SP_PARTICIPANTES_CAPACITACION_RETRIEVE_BY_CAPACITACION(Nullable<int> codigoCapacitacion)
        {
            var codigoCapacitacionParameter = codigoCapacitacion.HasValue ?
                new ObjectParameter("codigoCapacitacion", codigoCapacitacion) :
                new ObjectParameter("codigoCapacitacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_PARTICIPANTES_CAPACITACION_RETRIEVE_BY_CAPACITACION_Result>("SP_PARTICIPANTES_CAPACITACION_RETRIEVE_BY_CAPACITACION", codigoCapacitacionParameter);
        }
    }
}
